# ===================================================
# CONFIG SERVER OWN CONFIGURATION
# ===================================================

spring:
  application:
    name: config-server

server:
  port: 8888