spring:
  cloud:
    gateway:
      routes:
        - id: person-course-service-persons
          uri: lb://person-course-service
          predicates:
            - Path=/api/persons/**

        - id: person-course-service-courses
          uri: lb://person-course-service
          predicates:
            - Path=/api/courses/**

        - id: person-course-service-enrollments
          uri: lb://person-course-service
          predicates:
            - Path=/api/enrollments/**

        - id: person-course-service-swagger-ui
          uri: lb://person-course-service
          predicates:
            - Path=/swagger-ui/**

        - id: person-course-service-api-docs
          uri: lb://person-course-service
          predicates:
            - Path=/v3/api-docs/**