# ===================================================
# PERSON COURSE SERVICE CONFIGURATION
# ===================================================
spring:
  application:
    name: person-course-service
  datasource:
    url: jdbc:mysql://mysql:3306/schooldb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        one-indexed-parameters: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/school-realm
          jwk-set-uri: http://host.docker.internal:8180/realms/school-realm/protocol/openid-connect/certs

server:
  port: 8082

springdoc:
  swagger-ui:
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
  api-docs:
    path: /v3/api-docs